apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ddc-demo
  name: ddc-demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ddc-demo
  template:
    metadata:
      labels:
        app: ddc-demo
    spec:
      containers:
        - name: ddc-demo
          image: de.icr.io/vend-openshift/ddc-demo:v1
          env:
            - name: VEND_USAGE
              valueFrom:
                configMapKeyRef:
                  name: vend-usage
                  key: VEND_USAGE
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: vend-user-creds
                  key: VEND_USER
            - name: USERPASSWORD
              valueFrom:
                secretKeyRef:
                  name: vend-user-creds
                  key: VEND_USER_PASSWORD
            - name: ADMINUSER
              valueFrom:
                secretKeyRef:
                  name: vend-admin-creds
                  key: VEND_ADMIN
            - name: ADMINUSERPASSWORD
              valueFrom:
                secretKeyRef:
                  name: vend-admin-creds
                  key: VEND_ADMIN_PASSWORD
          volumeMounts:
            - mountPath: /usr/src/app/accesscodes
              name: vend-volume-accesscodes
            - mountPath: /usr/src/app/logs
              name: vend-volume-logs
          ports:
            - containerPort: 3000
      restartPolicy: Always
      imagePullSecrets:
        - name: impactsphere-qa-vend-ibm-id
